name: demoapp

replicaCount: 1

commands: []

containerPort: 8000

image:
  repository: kavinjaveriya/explorexdemo
  pullPolicy: Always
  tag: e816276

annotations:
  app: demoapp

labels:
  app: demoapp

matchLabels:
  app: demoapp

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

loadbalancer:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
