---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-lb
  {{- if .Values.loadbalancer.annotations }}
  annotations:
    {{- toYaml .Values.loadbalancer.annotations | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  selector:
    {{- toYaml .Values.matchLabels | nindent 4 }}